language: cpp
jobs:
  include:
    - name: "ARCH=arm32_v5 LLVM=1 LLVM_IAS=1"
      env: ARCH=arm32_v5 LLVM=1 LLVM_IAS=1
    - name: "ARCH=arm32_v6"
      env: ARCH=arm32_v6
    - name: "ARCH=arm32_v7 LLVM=1"
      env: ARCH=arm32_v7 LLVM=1
    - name: "ARCH=arm64 LLVM=1 LLVM_IAS=1"
      env: ARCH=arm64 LLVM=1 LLVM_IAS=1
    - name: "ARCH=mips"
      env: ARCH=mips
    - name: "ARCH=mipsel LD=ld.lld"
      env: ARCH=mipsel LD=ld.lld
    - name: "ARCH=ppc32"
      env: ARCH=ppc32
    - name: "ARCH=ppc64"
      env: ARCH=ppc64
    - name: "ARCH=ppc64le LD=ld.lld"
      env: ARCH=ppc64le LD=ld.lld
    - name: "ARCH=riscv BOOT=false LLVM_IAS=1"
      env: ARCH=riscv BOOT=false LLVM_IAS=1
    - name: "ARCH=s390 BOOT=false"
      env: ARCH=s390 BOOT=false
    - name: "ARCH=x86 LLVM=1 LLVM_IAS=1"
      env: ARCH=x86 LLVM=1 LLVM_IAS=1
    - name: "ARCH=x86_64 LLVM=1 LLVM_IAS=1"
      env: ARCH=x86_64 LLVM=1 LLVM_IAS=1
compiler: gcc
os: linux
install: skip
